version: '3.4'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server
    environment:
      SA_PASSWORD: "YourPassword"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"

  app:
    build:
      context: .
      dockerfile: MyDatabaseApp/Dockerfile
    depends_on:
      - sqlserver
    ports:
      - "80:80"